import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";
import { CONTACT_EMAIL, OPERATOR, SITE_NAME, SITE_DOMAIN } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Privacy Policy — Corkbored",
  description: "How Corkbored collects, uses, and protects your personal data.",
};

const BODY = `
${SITE_NAME} ("we", "us", "our") respects your privacy. This policy explains what
personal data we collect, why, how we use it, who we share it with, and the
rights you have over it. It applies to ${SITE_DOMAIN} and related services (the
"Service").

We grant the data-protection rights described here to **all** users regardless of
location. This policy is designed to meet the UK GDPR and EU GDPR, Canada's PIPEDA,
and the California Consumer Privacy Act (CCPA/CPRA).

## 1. Who is responsible for your data

The data controller is ${OPERATOR}. If you have any questions, or want to exercise
your rights, contact us at **${CONTACT_EMAIL}**.

## 2. What data we collect

**Account & profile data (via GitHub sign-in).** When you sign in with GitHub we
receive your GitHub user ID, username, display name, email address, and avatar
URL. We store an OAuth access token to act on your behalf where you ask us to
(e.g. sending repository collaborator invites).

**Profile information you provide.** Availability, hours per week, what you're
looking for, skills, and any links you add to your profile.

**Public GitHub statistics.** We may cache aggregate stats about your public
GitHub activity (account age, number of public repositories, recent public commit
counts, top languages) to display on your profile and projects.

**Content you create.** Projects, role listings, applications, announcements,
discussion threads and replies, chat messages, tasks, events, votes, follows, and
reports. Some of this content is public by nature of the Service.

**Communications.** Emails we send you (e.g. invites and notifications) and your
related preferences.

**Payment data.** If you purchase a paid feature (such as a project "boost"),
payment is processed by Stripe. We do **not** receive or store your full card
details — Stripe does. We receive confirmation and limited transaction metadata.

**Technical data.** Essential cookies needed for authentication and security (see
our [Cookie Policy](/cookies)), and standard server logs (such as IP address and
request metadata) generated by our hosting and database providers for security and
reliability.

## 3. How and why we use your data (legal bases)

| Purpose | Legal basis (GDPR) |
| --- | --- |
| Create and operate your account; provide the Service | Performance of a contract |
| Display your profile, projects, and content | Performance of a contract / legitimate interests |
| Send service emails (invites, application updates, announcements) | Performance of a contract / consent where required |
| Moderate content to keep the platform safe | Legitimate interests / legal obligation |
| Process payments for paid features | Performance of a contract |
| Secure the Service and prevent abuse | Legitimate interests / legal obligation |

Where we rely on consent (for example, optional notification emails), you can
withdraw it at any time.

## 4. Content moderation and AI processing

To keep the platform free of spam and abuse, some user-submitted text (such as
applications and announcements) is sent to **Anthropic** for automated
classification. This text is processed solely to produce a moderation verdict and
is not used to train third-party models under our arrangement. A human reviews
borderline cases.

## 5. Who we share your data with

We do not sell your personal data. We share it only with service providers
("processors") that help us run the Service, under contracts that require them to
protect it:

| Provider | Purpose | Location |
| --- | --- | --- |
| GitHub | Authentication and (optional) repository invites | US |
| Vercel | Application hosting | US / global |
| Neon | Database hosting | US / EU |
| Resend | Transactional email delivery | US |
| Anthropic | Automated content moderation | US |
| Stripe | Payment processing for paid features | US / global |

We may also disclose data where required by law, to enforce our Terms, or to
protect the rights, safety, or property of our users or others.

## 6. International transfers

We operate internationally and your data may be processed in countries outside
your own, including the United States. Where data is transferred out of the UK,
EEA, or other regions with data-export rules, we rely on appropriate safeguards
such as the providers' Standard Contractual Clauses and equivalent mechanisms.

## 7. How long we keep it

We keep your account data for as long as your account is active. If you delete your
account, we permanently delete your personal data and the content tied to it (see
Section 9), except where we must retain limited records to comply with legal
obligations (for example, tax records for payments) or to resolve disputes. Server
logs held by our providers are retained for a limited period.

## 8. Your rights

Depending on where you live, you have some or all of the following rights:

- **Access** — get a copy of the personal data we hold about you.
- **Rectification** — correct inaccurate or incomplete data.
- **Erasure** — delete your account and personal data ("right to be forgotten").
- **Restriction / Objection** — limit or object to certain processing, including
  processing based on legitimate interests.
- **Portability** — receive your data in a portable format.
- **Withdraw consent** — where processing is based on consent.

You can delete your account yourself at any time from your **Profile → Delete
account**. For any other request, email **${CONTACT_EMAIL}** and we will respond
within the time required by law (generally within 30 days). We will not discriminate
against you for exercising your rights.

If you are in the UK or EEA and believe we have mishandled your data, you may lodge
a complaint with your supervisory authority (in the UK, the Information
Commissioner's Office, ico.org.uk).

## 9. Deleting your account

When you delete your account, we permanently remove your profile, sign-in
credentials and tokens, and the content you authored. Projects that you solely own
are deleted along with their associated data. This action is irreversible. Some
content may persist in backups for a limited period before being overwritten.

## 10. California privacy rights (CCPA/CPRA)

If you are a California resident: in the past 12 months we have collected the
categories of personal information described in Section 2 (identifiers, internet
activity, and commercial information for paid features). We **do not sell or share**
your personal information as those terms are defined under the CCPA/CPRA. You have
the right to know, delete, and correct your personal information, and the right not
to be discriminated against for exercising these rights. Exercise them via
${CONTACT_EMAIL}.

## 11. Canadian privacy (PIPEDA)

If you are in Canada, we handle your personal information in accordance with PIPEDA.
You may request access to or correction of your information, and may direct
complaints to us at ${CONTACT_EMAIL} or to the Office of the Privacy Commissioner of
Canada.

## 12. Children

The Service is not directed to children. You must be at least 16 years old (or the
minimum age of digital consent in your country) to use it. We do not knowingly
collect data from children below that age; if you believe we have, contact us and we
will delete it.

## 13. Security

We use industry-standard measures to protect your data, including encrypted
connections and access controls. No system is perfectly secure, but we work to
protect your information and to notify you and the authorities where required if a
breach occurs.

## 14. Changes to this policy

We may update this policy from time to time. Material changes will be reflected by
updating the "Last updated" date above and, where appropriate, by notifying you.

## 15. Contact

Questions or requests: **${CONTACT_EMAIL}**.
`;

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" body={BODY} />;
}
